
name: TCI PROD update

on:
  workflow_dispatch:
    inputs:
      Deployment_type:
        description: Deployment-type
        required: true
        type: choice
        options:
        - Prod-Deployment
        - Rollback
      build_number:
        description: Build-number (Just the Number)
        required: true
      instance_count:
        description: Instance-Count
        required: true
        default: 0
      instance_name:
        description: Instance-Name
        required: false
      Sharedmodule_instance_name:
        description: Shared-module-Instance-Name
        required: false
      Change_number:
        description: ChangeNumber
        required: true

jobs:
  
  TCI-PROD:
    uses: Sanofi-GitHub/chc-devops-scripts/.github/workflows/TCI-PROD-Updated.yml@main
    with:
      DOCKER_IMAGE: 
        docker-chc-tibco-remote.artifactorydev.p230559371484.aws-emea.sanofi.com/build-images/sanofi-chc-build-base:v1.0.0
      INTERFACE_NAME: bw.mc-chc-Dummy_Timer
    secrets:
      CHC_HTTP_PROXY: ${{ secrets.CHC_HTTP_PROXY }}
      CHC_HTTPS_PROXY: ${{ secrets.CHC_HTTPS_PROXY }}
      CHC_GITHUB_PAT: ${{ secrets.CHC_GITHUB_PAT }}
      JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      PROD_TCI_CLIENT_ID: ${{ secrets.PROD_TCI_CLIENT_ID }}
      PROD_TCI_CLIENT_SECRET: ${{ secrets.PROD_TCI_CLIENT_SECRET }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
