
name: TCI DEV
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Branch Name
        required: true
      instance_count:
        description: Instance Count
        required: true
        default: 0

jobs:
  TCI-DEV:
    uses: Sanofi-GitHub/chc-devops-scripts/.github/workflows/TCI-DEV.yml@main
    with:
      DOCKER_IMAGE: docker-chc-tibco-remote.artifactorydev.p230559371484.aws-emea.sanofi.com/build-images/sanofi-chc-build-base:v1.0.0
      INTERFACE_NAME: bw.mc-WEBB-MATMAS
    secrets:
      CHC_HTTP_PROXY: ${{ secrets.CHC_HTTP_PROXY }}
      CHC_HTTPS_PROXY: ${{ secrets.CHC_HTTPS_PROXY }}
      CHC_GITHUB_PAT: ${{ secrets.CHC_GITHUB_PAT }}
      JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DEV_TCI_CLIENT_ID: ${{ secrets.DEV_TCI_CLIENT_ID }}
      DEV_TCI_CLIENT_SECRET: ${{ secrets.DEV_TCI_CLIENT_SECRET }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
